apiVersion: v1
kind: ServiceAccount
metadata:
  name: analytics-service
  namespace: analytics
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::000000000000:role/togglemaster-analytics-service
