apiVersion: v1
kind: ServiceAccount
metadata:
  name: evaluation-service
  namespace: evaluation
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::579097996347:role/ToggleMasterEvaluationServiceRole
